name: Build Geode Mod

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Geode
        uses: geode-sdk/cli@main
        with:
          version: stable

      - name: Build
        run: geode build

      - name: Upload mod
        uses: actions/upload-artifact@v4
        with:
          name: PhysicsIndicator
          path: build/*.geode
